### ISSUE TITLE
最新代码解析优酷vip视频仍只有6s且无4k

### ISSUE THREAD

**Issue by affvps** [Tontonnow/ttt#1]
none

**Comment by Priveete** [comment]
@affvps 大佬如何解决这个问题的
![image](https://github.com/Tontonnow/ttt/assets/91370754/0c8d26b6-1844-4b1f-be09-8523d2def2e9)

**Comment by affvps** [comment]
> @affvps 大佬如何解决这个问题的，截图报错如下 ![image](https://user-images.githubusercontent.com/91370754/279918890-0c8d26b6-1844-4b1f-be09-8523d2def2e9.png)

按错误提示修改cdm.py
