### ISSUE TITLE
爱奇艺同一剧集解析最高分辨率不一样，不知道是什么问题？

### ISSUE THREAD

**Issue by xztxy** [Tontonnow/ttt#2]
大佬您好，发现爱奇艺解析剧集的时候，最高分辨率都不一样，不知道是什么情况。
1![image](https://github.com/Tontonnow/ttt/assets/31698398/4cd94f74-6d69-4aed-8601-edc7e369cc18)
2![image](https://github.com/Tontonnow/ttt/assets/31698398/afcc0e04-46f6-4441-89c2-eea71ea17d86)
3![image](https://github.com/Tontonnow/ttt/assets/31698398/72170205-9fa0-4b17-8965-c79fecf15817)
4![image](https://github.com/Tontonnow/ttt/assets/31698398/67fe96c4-3f40-4cf2-9ac2-23274983556a)
5![image](https://github.com/Tontonnow/ttt/assets/31698398/d03ca55d-1db4-4ec7-84b4-7b5a7031a2f1)
6![image](https://github.com/Tontonnow/ttt/assets/31698398/f288fb50-5874-42d9-a14c-5467db62c723)
7![image](https://github.com/Tontonnow/ttt/assets/31698398/fe1ef7c5-4e73-486e-9f3b-e0a2baa6b28a)
20![image](https://github.com/Tontonnow/ttt/assets/31698398/5880b695-c288-4624-ab9d-0228adc46323)
35![image](https://github.com/Tontonnow/ttt/assets/31698398/911fabe3-f10b-44d1-9261-6b4b1931f082)

**Comment by moyuaa** [comment]
我直接运行报错，可以联系一下你，问些问题吗

**Comment by marysue2496651238** [comment]
我也出现了最高分辨率不同的情况
