### ISSUE TITLE
大佬，优酷的copyrightdrm视频只有6分钟

### ISSUE THREAD

**Issue by ChrisShen-github** [Tontonnow/ttt#6]
![yk](https://github.com/Tontonnow/ttt/assets/37608623/c0e2b50f-0e6e-48e6-bc10-351eebbf0d8d)
![yk1](https://github.com/Tontonnow/ttt/assets/37608623/d6fe5855-2fc5-469c-ab02-13840ef6f426)

**Comment by Tontonnow** [comment]
hq需要酷喵会员或者帧享会员，这是安装包 lanzouy.com/iiAz21fvrgfg 建议用雷电模拟器安卓5

**Comment by Priveete** [comment]
@Tontonnow 大佬，这是啥报错？
![image](https://github.com/Tontonnow/ttt/assets/91370754/69fe18e1-c0f8-4ee4-a208-860706b3c3ee)

**Comment by xztxy** [comment]
> 这是安装包 lanzouy.com/iiAz21fvrgfg 建议用

大佬请问下。我是酷喵会员。下载后混流出现这个错误，最后播放只有前面1分50S正常播放 是什么问题呢？
![image](https://github.com/Tontonnow/ttt/assets/31698398/ddc9bb95-5b3a-4da5-b9ea-a95250e8e5f5)

**Comment by Tontonnow** [comment]
> > 这是安装包 lanzouy.com/iiAz21fvrgfg 建议用
> 
> 大佬请问下。我是酷喵会员。下载后混流出现这个错误，最后播放只有前面1分50S正常播放 是什么问题呢？ ![image](https://private-user-images.githubusercontent.com/31698398/285567759-ddc9bb95-5b3a-4da5-b9ea-a95250e8e5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA4OTE5NDUsIm5iZiI6MTcwMDg5MTY0NSwicGF0aCI6Ii8zMTY5ODM5OC8yODU1Njc3NTktZGRjOWJiOTUtNWIzYS00ZGE1LWI5ZWEtYTk1MjUwZThlNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI1VDA1NTQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwMGQwNjJlNTMzNDNiYmQwMTM1MmQzNGYyMzNiNWY4NTllMWU3NTE5NDJmNDk0MjZhYzEwNjFkNjE5MTFjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AhaW83jiSLUEzVYoAfWBd6__UL36Cid1FnTR2k-BCpc)

key写的有点问题，更新了，或者你自己手动替换一下bat命令里的key

**Comment by ChrisShen-github** [comment]
感谢大佬
